apiVersion: v1
kind: Service
metadata:
  name: demo-flask-service
  namespace: demo-app
spec:
  selector:
    app: demo-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort